services:
  # 1. Tahmin API Servisi
  api:
    build: .
    container_name: nyc_taxi_api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models  # Modelleri güncellersek container'ı yeniden yapmaya gerek kalmasın
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow

  # 2. MLflow Sunucusu (Deney Takibi İçin)
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.10.0
    container_name: nyc_taxi_mlflow
    ports:
      - "5001:5000"
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 0.0.0.0